# -*- coding: utf-8 -*-
"""Microsservico_do_calculo_ver.beta2.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WR526S5xL2TFKPANCS1azJlBYzG-Gac_
"""

# Importando as bibliotecas
import math

# Função que realizará o cálculo da sensibilidade insulínica para pacientes com
# diabetes tipo 1
def calcular_eiS_T1D(cintura, doseinsulina, adiponectina, triglicerideos, dbp):
  # Calcula o valor da expressão na exponencial
  valor_exponencial_T1D = 4.06154 + (-0.01317 * cintura) + \
                      (-1.09615 * doseinsulina) + \
                      (0.02027 * adiponectina) + \
                      (-0.00307 * triglicerideos) + \
                      (-0.00733 * dbp)

  # Calcula a exponencial
  eiS_T1D = math.exp(valor_exponencial_T1D)
  return eiS_T1D

# Função que realizará o cálculo da sensibilidade insulínica para pacientes sem
# diabetes
def calcular_eiS_nonDiabetic(cintura, hba1c, glicose_jejum, adiponectina,
                             triglicerideos, dbp):
 # Calcula o valor da expressao na exponencial
 valor_exponencial_nonDiabetic = 7.47237 + (-0.01275 * cintura) + \
                            (-0.24990 * hba1c) + (-0.01983 * glicose_jejum) + \
                            (0.01905 * adiponectina) + \
                            (-0.00324 * triglicerideos) + (-0.00588 * dbp)

 # Calcula a exponencial
 eis_nonDiabetic = math.exp(valor_exponencial_nonDiabetic)
 return eis_nonDiabetic

# Entrada dos dados clínicos do paciente
cintura = float(input("Valor da circunferência da cintura em centímetros : "))
peso_corporal = float(input("Valor do peso corporal em quilogramas : "))
unidades_diarias = float(input("Quantidade de unidades diárias de insulina : "))
doseinsulina = unidades_diarias/peso_corporal
hba1c = float(input("Valor da HbA1c em porcentagem : "))
glicose_jejum = float(input("Valor da glicose medida em jejum em miligramas "
                          "por decilitro : "))
adiponectina = float(input("Valor dos níveis de adiponectina em "
                          "microgramas por mililitro : "))
triglicerideos = float(input("Valor dos níveis de triglicerídeos em "
                          "miligramas por decilitro : "))
dbp = float(input("Valor da DBP em milímetro de mercúrio : "))

# Calcula o valor da sensibilidade insulínica para pacientes com diabetes
# tipo 1
resultado_eiS_T1D = calcular_eiS_T1D(cintura, doseinsulina, adiponectina,
                             triglicerideos, dbp)
# Calcula o valor da sensibilidade insulínica para pacientes sem diabetes
resultado_eiS_nonDiabetic = calcular_eiS_nonDiabetic(cintura, hba1c,
                            glicose_jejum, adiponectina, triglicerideos, dbp)

# Exibe o resultado obtido da sensibilidade insulínica para pacientes com
# diabetes tipo 1
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "com diabetes tipo 1: {:.3f}".format(resultado_eiS_T1D))
# Exibe o resultado obtido da sensibilidade insulínica para pacientes sem
# diabetes
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "sem diabetes: {:.3f}".format(resultado_eiS_nonDiabetic))