# -*- coding: utf-8 -*-
"""Microsservico_do_calculo_ver.beta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhXW-RH5spGFU4sBs-sVyuPkfP2SqUa9
"""

# Importando as bibliotecas
import math

# Função que realizará o Cálculo da Sensibilidade Insulínica
def calcular_eiS(cintura, doseinsulina, adiponectina, triglicerideos, dbp):
  # Definição das constantes usadas no cálculo
  constante = 4.06154
  constante_cintura = -0.01317
  constante_doseinsulina = -1.09615
  constante_adiponectina = 0.02027
  constante_triglicerideos = -0.00307
  constante_dbp = -0.00733

  # Calcula o valor da expressão na exponencial
  valor_exponencial = constante + (constante_cintura * cintura) + \
                      (constante_doseinsulina * doseinsulina) + \
                      (constante_adiponectina * adiponectina) + \
                      (constante_triglicerideos * triglicerideos) + \
                      (constante_dbp * dbp)

  # Calcula a exponencial
  eiS = math.exp(valor_exponencial)
  return eiS

# Entrada dos dados clínicos do paciente
cintura = float(input("Valor da circunferência da cintura em centímetros : "))
peso_corporal = float(input("Valor do peso corporal em quilogramas : "))
unidades_diarias = float(input("Quantidade de unidades diárias de insulina : "))
doseinsulina = unidades_diarias/peso_corporal
adiponectina = float(input("Valor dos níveis de adiponectina em "
                          "microgramas por mililitro : "))
triglicerideos = float(input("Valor dos níveis de triglicerídeos em "
                          "miligramas por decilitro : "))
dbp = float(input("Valor da DBP em milímetro de Mercúrio : "))

# Calcula o valor da Sensibilidade Insulínica
resultado_eiS = calcular_eiS(cintura, doseinsulina, adiponectina,
                             triglicerideos, dbp)

# Exibe o resultado obtido da sensibilidade insulínica
print("Valor calculado da "
      "sensibilidade insulíninca : {:.3f}".format(resultado_eiS))