# -*- coding: utf-8 -*-
"""Microsservico_do_calculo_ver.beta3.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dvl0GQzCR1ywp-UG6DBNV76Nf_tHopIJ
"""

# Importando as bibliotecas
import math

# Função que realizará o cálculo da sensibilidade insulínica para pacientes com
# diabetes tipo 1
def calcular_eiS_T1D(cintura, doseinsulina, adiponectina, triglicerideos, dbp):
  # Calcula o valor da expressão na exponencial
  valor_exponencial_T1D = 4.06154 + (-0.01317 * cintura) + \
                      (-1.09615 * doseinsulina) + \
                      (0.02027 * adiponectina) + \
                      (-0.00307 * triglicerideos) + \
                      (-0.00733 * dbp)

  # Calcula a exponencial
  eiS_T1D = math.exp(valor_exponencial_T1D)
  return eiS_T1D

# Função que realizará o cálculo da sensibilidade insulínica para pacientes com
# diabetes tipo 1 que não fizeram jejum
def calcular_eiS_T1D_nonfasting(doseinsulina, cintura):
  # Calcula o valor da expressão na exponencial
  valor_exponencial_T1D_nonfasting = 4.61476 + (-1.53803 * doseinsulina) + \
                      (-0.02506 * cintura)

  # Calcula a exponencial
  eiS_T1D_nonfasting = math.exp(valor_exponencial_T1D_nonfasting)
  return eiS_T1D_nonfasting

# Função que realizará o cálculo da sensibilidade insulínica para pacientes com
# diabetes tipo 1 sem os valores de adiponectina
def calcular_eiS_T1D_exAdiponectina(cintura, doseinsulina, triglicerideos, dbp):
  # Calcula o valor da expressão na exponencial
  valor_exponencial_T1D_exAdiponectina = 4.1075 + (-0.01299 * cintura) + \
                      (-1.05819 * doseinsulina) + \
                      (-0.00354 * triglicerideos) + \
                      (-0.00802 * dbp)

  # Calcula a exponencial
  eiS_T1D_exAdiponectina = math.exp(valor_exponencial_T1D_exAdiponectina)
  return eiS_T1D_exAdiponectina

# Função que realizará o cálculo da sensibilidade insulínica para pacientes sem
# diabetes
def calcular_eiS_nonDiabetic(cintura, hba1c, glicosejejum, adiponectina,
                             triglicerideos, dbp):
 # Calcula o valor da expressao na exponencial
 valor_exponencial_nonDiabetic = 7.47237 + (-0.01275 * cintura) + \
                            (-0.24990 * hba1c) + (-0.01983 * glicosejejum) + \
                            (0.01905 * adiponectina) + \
                            (-0.00324 * triglicerideos) + (-0.00588 * dbp)

 # Calcula a exponencial
 eis_nonDiabetic = math.exp(valor_exponencial_nonDiabetic)
 return eis_nonDiabetic

# Função que realizará o cálculo da sensibilidade insulínica para pacientes sem
# diabetes que não fizeram jejum
def calcular_eiS_nonDiabetic_nonfasting(sexobiologico_bit, hba1c, cintura):
 # Calcula o valor da expressao na exponencial
 valor_exponencial_nonDiabetic_nonfasting = 6.10604 + \
                            (0.2117 * sexobiologico_bit) + \
                            (-0.28233 * hba1c) + (-0.02293 * cintura)

 # Calcula a exponencial
 eis_nonDiabetic_nonfasting = math.exp(valor_exponencial_nonDiabetic_nonfasting)
 return eis_nonDiabetic_nonfasting

# Função que realizará o cálculo da sensibilidade insulínica para pacientes sem
# diabetes sem os valores de adiponectina
def calcular_eiS_nonDiabetic_exAdiponectina(sexobiologico_bit, cintura,
                                            hba1c, glicosejejum,
                                            triglicerideos):
 # Calcula o valor da expressao na exponencial
 valor_exponencial_nonDiabetic_exAdiponectina = 7.19138 + \
                            (0.10173 * sexobiologico_bit) + \
                            (-0.01414 * cintura) + (-0.33308 * hba1c) + \
                            (-0.01290 * glicosejejum) + \
                            (-0.00316 * triglicerideos)

 # Calcula a exponencial
 eis_nonDiabetic_exAdiponectina = math.exp(valor_exponencial_nonDiabetic_exAdiponectina)
 return eis_nonDiabetic_exAdiponectina

# Entrada dos dados clínicos do paciente
cintura = float(input("Valor da circunferência da cintura em centímetros : "))
peso_corporal = float(input("Valor do peso corporal em quilogramas : "))
unidades_diarias = float(input("Quantidade de unidades diárias de insulina : "))
doseinsulina = unidades_diarias/peso_corporal
while True:
  sexobiologico = input("Sexo biológico do paciente (Masculino/Feminino) : ")
  if sexobiologico == "Masculino":
    sexobiologico_bit = 1
    break
  elif sexobiologico == "Feminino":
    sexobiologico_bit = 0
    break
  else:
    print("Por favor, insira Masculino ou Feminino. ")
hba1c = float(input("Valor da HbA1c em porcentagem : "))
glicosejejum = float(input("Valor da glicose medida em jejum em miligramas "
                          "por decilitro : "))
adiponectina = float(input("Valor dos níveis de adiponectina em "
                          "microgramas por mililitro : "))
triglicerideos = float(input("Valor dos níveis de triglicerídeos em "
                          "miligramas por decilitro : "))
dbp = float(input("Valor da DBP em milímetro de mercúrio : "))

# Calcula o valor da sensibilidade insulínica para pacientes com diabetes
# tipo 1
resultado_eiS_T1D = calcular_eiS_T1D(cintura, doseinsulina, adiponectina,
                             triglicerideos, dbp)

# Calcula o valor da sensibilidade insulínica para pacientes com diabetes
# tipo 1 que não fizeram jejum
resultado_eiS_T1D_nonfasting = calcular_eiS_T1D_nonfasting(doseinsulina,
                                                           cintura)

# Calcula o valor da sensibilidade insulínica para pacientes com diabetes
# tipo 1 que não possuem os valores de adiponectina
resultado_eiS_T1D_exAdiponectina = calcular_eiS_T1D_exAdiponectina(cintura,
                                                                doseinsulina,
                                                                triglicerideos,
                                                                dbp)

# Calcula o valor da sensibilidade insulínica para pacientes sem diabetes
resultado_eiS_nonDiabetic = calcular_eiS_nonDiabetic(cintura, hba1c,
                            glicosejejum, adiponectina, triglicerideos, dbp)

# Calcula o valor da sensibilidade insulínica para pacientes sem diabetes
# e que não fizeram jejum
resultado_eiS_nonDiabetic_nonfasting = calcular_eiS_nonDiabetic_nonfasting(
                                                              sexobiologico_bit,
                                                              hba1c, cintura)

# Calcula o valor da sensibilidade insulínica para pacientes sem diabetes
# e que não possuem os valores de adiponectina
resultado_eiS_nonDiabetic_exAdiponectina = calcular_eiS_nonDiabetic_exAdiponectina(
                                                              sexobiologico_bit,
                                                              cintura, hba1c,
                                                              glicosejejum,
                                                              triglicerideos)

# Exibe o resultado obtido da sensibilidade insulínica para pacientes com
# diabetes tipo 1
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "com diabetes tipo 1: {:.3f}".format(resultado_eiS_T1D))

# Exibe o resultado obtido da sensibilidade insulínica para pacientes com
# diabetes tipo 1 que não fizeram jejum
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "com diabetes tipo 1 que "
      "não fizeram jejum: {:.3f}".format(resultado_eiS_T1D_nonfasting))

# Exibe o resultado obtido da sensibilidade insulínica para pacientes com
# diabetes tipo 1 que não possuem os valores de adiponectina
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "com diabetes tipo 1 que "
      "não possuem os valores de "
      "adiponectina: {:.3f}".format(resultado_eiS_T1D_exAdiponectina))

# Exibe o resultado obtido da sensibilidade insulínica para pacientes sem
# diabetes
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "sem diabetes: {:.3f}".format(resultado_eiS_nonDiabetic))

# Exibe o resultado obtido da sensibilidade insulínica para pacientes sem
# diabetes e que não fizeram jejum
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "sem diabetes e que não fizeram "
      "jejum: {:.3f}".format(resultado_eiS_nonDiabetic_nonfasting))

# Exibe o resultado obtido da sensibilidade insulínica para pacientes sem
# diabetes e que possuem os valores de adiponectina
print("Valor calculado da "
      "sensibilidade insulíninca para pacientes "
      "sem diabetes e que não possuem os valores de "
      "adiponectina: {:.3f}".format(resultado_eiS_nonDiabetic_exAdiponectina))