# -*- coding: utf-8 -*-
"""Microsservico_do_calculo_ver.alpha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_eUD4PQed8qX68QYBuRIOEKDMX7FAR2
"""

# Importando as bibliotecas
import math

# Função que realizará o Cálculo da Sensibilidade Insulínica
def calcular_eiS(cintura, doseinsulina, adiponectina, triglicerideos, dbp):
  # Definição das constantes usadas no cálculo
  constante = 4.06154
  constante_cintura = -0.01317
  constante_doseinsulina = -1.09615
  constante_adiponectina = 0.02027
  constante_triglicerideos = -0.27168
  constante_dbp = -0.00733

  # Calcula o valor da expressão na exponencial
  valor_exponencial = constante + (constante_cintura * cintura) + \
                      (constante_doseinsulina * doseinsulina) + \
                      (constante_adiponectina * adiponectina) + \
                      (constante_triglicerideos * triglicerideos) + \
                      (constante_dbp * dbp)

  # Calcula a exponencial
  eiS = math.exp(valor_exponencial)
  return eiS

# Entrada dos dados clínicos do paciente
cintura = float(input())
doseinsulina = float(input())
adiponectina = float(input())
triglicerideos = float(input())
dbp = float(input())

# Calcula o valor da Sensibilidade Insulínica
resultado_eiS = calcular_eiS(cintura, doseinsulina, adiponectina,
                             triglicerideos, dbp)

# Exibe o resultado obtido
print(resultado_eiS)